### ISSUE TITLE
Некорректная обработка ввода

### ISSUE THREAD

**Issue by finomen** [KrasnovPavel/HomeWorks#1]
Enter expression for calculation or enter empty string for quit:
3-4
3-4 = 3

**Comment by KrasnovPavel** [comment]
Некорректная входная строка. Программа работает правильно.

**Comment by finomen** [comment]
Нет, неправильно. Она должна сообщить о некорректном вводе

**Comment by KrasnovPavel** [comment]
Исправлено в последнем коммите.
